"""Input/Output validation guardrails for Teamfair AI agent server.

Provides multi-layer security validation (regex, heuristics, PII redaction, output canary checks)
to protect against prompt injection, jailbreaks, and sensitive data leakage.
"""

from __future__ import annotations

import re
from typing import Any

# Regex patterns for direct prompt injection & system prompt override detection
PROMPT_INJECTION_PATTERNS = [
    re.compile(r"ignore\s+(?:all\s+)?previous\s+instructions", re.IGNORECASE),
    re.compile(r"override\s+your\s+system\s+(?:prompt|instructions)", re.IGNORECASE),
    re.compile(r"you\s+are\s+now\s+(?:a|an)\s+", re.IGNORECASE),
    re.compile(r"forget\s+(?:all\s+)?prior\s+rules", re.IGNORECASE),
    re.compile(r"system\s+(?:prompt|instructions|rules)\s*[:=]", re.IGNORECASE),
    re.compile(r"output\s+(?:your\s+)?system\s+(?:prompt|instructions|rules)", re.IGNORECASE),
    re.compile(r"leak\s+(?:your\s+)?system\s+(?:prompt|instructions|rules)", re.IGNORECASE),
    re.compile(r"reveal\s+(?:your\s+)?system\s+(?:prompt|instructions|rules)", re.IGNORECASE),
    re.compile(r"translate\s+your\s+system\s+instructions", re.IGNORECASE),
    re.compile(r"dan\s+mode", re.IGNORECASE),
    re.compile(r"jailbreak", re.IGNORECASE),
    re.compile(r"new\s+instructions\s*[:=]", re.IGNORECASE),
    re.compile(r"developer\s+mode", re.IGNORECASE),
]

# PII Redaction Regexes
EMAIL_REGEX = re.compile(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+")
PHONE_REGEX = re.compile(r"\+?[0-9][0-9\-\s\(\)]{8,16}[0-9]")
# Detect potential secrets like bearer tokens, service role keys, API keys
SECRET_REGEX = re.compile(
    r"(?:sk-proj-|sbp_|eyJhbGciOi)[a-zA-Z0-9\-_=]{16,}", re.IGNORECASE
)


def redact_pii(text: str) -> str:
    """Redacts emails, phone numbers, and potential API keys/secrets from text."""
    text = EMAIL_REGEX.sub("<REDACTED_EMAIL>", text)
    text = PHONE_REGEX.sub("<REDACTED_PHONE>", text)
    text = SECRET_REGEX.sub("<REDACTED_SECRET>", text)
    return text


def score_heuristics(text: str) -> dict[str, Any]:
    """Calculates heuristic anomaly scores for prompt injection signs.

    Returns score (0.0 to 1.0) and lists of triggered structural rules.
    """
    triggered_rules = []
    score_sum = 0.0

    # 1. Check special character ratio (indicative of encoding / obfuscation)
    if text:
        alpha_num_count = sum(1 for c in text if c.isalnum() or c.isspace())
        special_ratio = 1.0 - (alpha_num_count / len(text))
        if special_ratio > 0.35:
            score_sum += 0.4
            triggered_rules.append(f"high_special_char_ratio_{special_ratio:.2f}")

    # 2. Check for extreme uppercase ratio (instruction shouting)
    alpha_chars = [c for c in text if c.isalpha()]
    if alpha_chars:
        upper_ratio = sum(1 for c in alpha_chars if c.isupper()) / len(alpha_chars)
        if upper_ratio > 0.65 and len(alpha_chars) > 10:
            score_sum += 0.3
            triggered_rules.append("excessive_capitalization")

    # 3. Check for multiple distinct language script components (mixing/obfuscation)
    # E.g. Cyrillic/Greek character mixing within Latin words
    has_mixed_scripts = False
    latin_chars = len(re.findall(r"[a-zA-Z]", text))
    other_scripts = len(re.findall(r"[\u0400-\u04FF\u0370-\u03FF]", text))  # Cyrillic/Greek
    if latin_chars > 0 and other_scripts > 0:
        has_mixed_scripts = True
        score_sum += 0.5
        triggered_rules.append("mixed_alphabet_scripts")

    return {
        "anomaly_score": min(score_sum, 1.0),
        "triggered_rules": triggered_rules,
    }


def validate_input(user_message: str) -> dict[str, Any]:
    """Inspects and sanitizes user input before passing to the LLM.

    Returns:
        dict: {"safe": bool, "sanitized_input": str, "reason": str | None}
    """
    sanitized = redact_pii(user_message)

    # 1. Run Regex check for known prompt injections
    for pattern in PROMPT_INJECTION_PATTERNS:
        if pattern.search(user_message):
            return {
                "safe": False,
                "sanitized_input": sanitized,
                "reason": f"Triggered injection pattern: {pattern.pattern}",
            }

    # 2. Run Heuristics check
    heuristics = score_heuristics(user_message)
    if heuristics["anomaly_score"] >= 0.7:
        return {
            "safe": False,
            "sanitized_input": sanitized,
            "reason": f"High anomaly score ({heuristics['anomaly_score']}): {', '.join(heuristics['triggered_rules'])}",
        }

    return {
        "safe": True,
        "sanitized_input": sanitized,
        "reason": None,
    }


def validate_output(response_text: str, canary_token: str | None = None) -> dict[str, Any]:
    """Inspects response text generated by the LLM to prevent data leakage/jailbreaks.

    Returns:
        dict: {"safe": bool, "validated_response": str, "fallback_response": str}
    """
    fallback = "Tôi không thể hoàn thành yêu cầu này do chính sách bảo mật."

    # 1. Canary check
    if canary_token and canary_token in response_text:
        return {
            "safe": False,
            "validated_response": fallback,
            "fallback_response": fallback,
        }

    # 2. Redact any sensitive information accidentally leaked
    sanitized_response = redact_pii(response_text)

    # 3. Check if system instructions were leaked verbatim
    system_prompt_snippets = [
        "student thesis workspace assistant for Teamfair",
        "Kanban / tasks — list, create, update status",
        "Prefer calling tools to fetch ground truth",
    ]
    for snippet in system_prompt_snippets:
        if snippet.lower() in response_text.lower():
            return {
                "safe": False,
                "validated_response": fallback,
                "fallback_response": fallback,
            }

    return {
        "safe": True,
        "validated_response": sanitized_response,
        "fallback_response": fallback,
    }
